### ISSUE TITLE
Отчет 4 Лаба

### ISSUE THREAD

**Issue by oleg-tgn** [Gnojnyj17/OAIP_LABS_Babichev#1]
1) Форматирование текста, читайте внимательно описание в вики
- нет отступов в первых строках
- убрать интервалы между абзацами
- блок с алгоритмом работы куда-то уехал сильно вправо

2) Алгоритм. Слишком обще описан. Если не пишите блок-схемы пишите в виде псевдо-кода, чтобы по вашему алгоритму можно было легко понять как работает код

3) Заключение должно прямо следовать из Цели работы. Цель работы нужно взять из методички

**Comment by Gnojnyj17** [comment]
Сделал #1
